module lk.ijse.serenitymentalhealth {
    requires javafx.controls;
    requires javafx.fxml;
    requires static lombok;
    requires jakarta.persistence;
    requires org.hibernate.orm.core;
    requires java.naming;
    requires java.sql;
    //requires lk.ijse.serenitymentalhealth;
    requires javafx.base;
    requires javafx.graphics;
    requires com.google.protobuf;
    requires mysql.connector.j;
    requires jbcrypt;
    //requires lk.ijse.serenitymentalhealth;
    //requires lk.ijse.serenitymentalhealth;
    //requires lk.ijse.serenitymentalhealth;
    //requires lk.ijse.serenitymentalhealth;
    //requires lk.ijse.serenitymentalhealth;
    //requires lk.ijse.serenitymentalhealth;
    //requires lk.ijse.serenitymentalhealth;
    //requires lk.ijse.serenitymentalhealth;
    //requires lk.ijse.serenitymentalhealth;
    //requires lk.ijse.serenitymentalhealth;
    //requires lk.ijse.serenitymentalhealth;
    //requires lk.ijse.serenitymentalhealth;
    //requires lk.ijse.serenitymentalhealth;
    //requires lk.ijse.serenitymentalhealth;
    //requires lk.ijse.serenitymentalhealth;
    //requires lk.ijse.serenitymentalhealth;
    //requires lk.ijse.serenitymentalhealth;
    //requires lk.ijse.serenitymentalhealth;
    //requires lk.ijse.serenitymentalhealth;
    //requires lk.ijse.serenitymentalhealth;
    //requires lk.ijse.serenitymentalhealth;
    //requires lk.ijse.serenitymentalhealth;
    //requires lk.ijse.serenitymentalhealth;
    //requires lk.ijse.serenitymentalhealth;
    //requires lk.ijse.serenitymentalhealth;
    //requires lk.ijse.serenitymentalhealth;
    //requires lk.ijse.serenitymentalhealth;
    //requires lk.ijse.serenitymentalhealth;
    //requires lk.ijse.serenitymentalhealth;
    //requires lk.ijse.serenitymentalhealth;
    //requires lk.ijse.serenitymentalhealth;
    //requires lk.ijse.serenitymentalhealth;
    //requires lk.ijse.serenitymentalhealth;

    opens lk.ijse.serenitymentalhealth to javafx.fxml;
    opens lk.ijse.serenitymentalhealth.controller to javafx.fxml;
    opens lk.ijse.serenitymentalhealth.dto to javafx.base;
    opens lk.ijse.serenitymentalhealth.entity to org.hibernate.orm.core;
    opens lk.ijse.serenitymentalhealth.enums to org.hibernate.orm.core;

    exports lk.ijse.serenitymentalhealth;
}